<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class COASeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('account_categories')->insert([
            [
                'id' => 1,
                'company_id' => 1,
                'name' => 'Kas & Bank',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'company_id' => 1,
                'name' => 'Akun Piutang',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'company_id' => 1,
                'name' => 'Persediaan',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'company_id' => 1,
                'name' => 'Aktiva Lancar Lainnya',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'company_id' => 1,
                'name' => 'Aktiva Tetap',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'company_id' => 1,
                'name' => 'Depresiasi & Armortisasi',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'company_id' => 1,
                'name' => 'Aktiva Lainnya',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'company_id' => 1,
                'name' => 'Akun Hutang',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'company_id' => 1,
                'name' => 'Kewajiban Lancar Lainnya',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'company_id' => 1,
                'name' => 'Kewajiban Jangka Panjang',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'company_id' => 1,
                'name' => 'Ekuitas',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'company_id' => 1,
                'name' => 'Pendapatan',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'company_id' => 1,
                'name' => 'Harga Pokok Penjualan',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'company_id' => 1,
                'name' => 'Beban',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'company_id' => 1,
                'name' => 'Pendapatan Lainnya',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'company_id' => 1,
                'name' => 'Beban Lainnya',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'company_id' => 1,
                'name' => 'Kartu Kredit',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('chart_of_accounts')->insert([
            [
                'id' => 1,
                'company_id' => 1,
                'category_id' => 1,
                'name' => 'Kas',
                'code' => '1-10001',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'company_id' => 1,
                'category_id' => 1,
                'name' => 'Rekening Bank',
                'code' => '1-10002',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'company_id' => 1,
                'category_id' => 1,
                'name' => 'Giro',
                'code' => '1-10003',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'company_id' => 1,
                'category_id' => 2,
                'name' => 'Piutang Usaha',
                'code' => '1-10100',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'company_id' => 1,
                'category_id' => 2,
                'name' => 'Piutang Belum Ditagih',
                'code' => '1-10101',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'company_id' => 1,
                'category_id' => 2,
                'name' => 'Cadangan Kerugian Piutang',
                'code' => '1-10102',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'company_id' => 1,
                'category_id' => 3,
                'name' => 'Persediaan Barang',
                'code' => '1-10200',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'company_id' => 1,
                'category_id' => 4,
                'name' => 'Piutang Lainnya',
                'code' => '1-10300',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'company_id' => 1,
                'category_id' => 4,
                'name' => 'Piutang Karyawan',
                'code' => '1-10301',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'company_id' => 1,
                'category_id' => 4,
                'name' => 'Dana Belum Disetor',
                'code' => '1-10400',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'company_id' => 1,
                'category_id' => 4,
                'name' => 'Aset Lancar Lainnya',
                'code' => '1-10401',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'company_id' => 1,
                'category_id' => 4,
                'name' => 'Biaya Dibayar Di Muka',
                'code' => '1-10402',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'company_id' => 1,
                'category_id' => 4,
                'name' => 'Uang Muka',
                'code' => '1-10403',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'company_id' => 1,
                'category_id' => 4,
                'name' => 'PPN Masukan',
                'code' => '1-10500',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'company_id' => 1,
                'category_id' => 4,
                'name' => 'Pajak Dibayar Di Muka - PPh 22',
                'code' => '1-10501',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'company_id' => 1,
                'category_id' => 4,
                'name' => 'Pajak Dibayar Di Muka - PPh 23',
                'code' => '1-10502',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'company_id' => 1,
                'category_id' => 4,
                'name' => 'Pajak Dibayar Di Muka - PPh 25',
                'code' => '1-10503',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'company_id' => 1,
                'category_id' => 5,
                'name' => 'Aset Tetap - Tanah',
                'code' => '1-10700',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'company_id' => 1,
                'category_id' => 5,
                'name' => 'Aset Tetap - Bangunan',
                'code' => '1-10701',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'company_id' => 1,
                'category_id' => 5,
                'name' => 'Aset Tetap - Building Improvements',
                'code' => '1-10702',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'company_id' => 1,
                'category_id' => 5,
                'name' => 'Aset Tetap - Kendaraan',
                'code' => '1-10703',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'company_id' => 1,
                'category_id' => 5,
                'name' => 'Aset Tetap - Mesin & Peralatan',
                'code' => '1-10704',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'company_id' => 1,
                'category_id' => 5,
                'name' => 'Aset Tetap - Perlengkapan Kantor',
                'code' => '1-10705',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'company_id' => 1,
                'category_id' => 5,
                'name' => 'Aset Tetap - Aset Sewa Guna Usaha',
                'code' => '1-10706',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'company_id' => 1,
                'category_id' => 5,
                'name' => 'Aset Tak Berwujud',
                'code' => '1-10707',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'company_id' => 1,
                'category_id' => 6,
                'name' => 'Akumulasi Penyusutan - Bangunan',
                'code' => '1-10751',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'company_id' => 1,
                'category_id' => 6,
                'name' => 'Akumulasi Penyusutan - Building Improvements',
                'code' => '1-10752',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'company_id' => 1,
                'category_id' => 6,
                'name' => 'Akumulasi penyusutan - Kendaraan',
                'code' => '1-10753',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'company_id' => 1,
                'category_id' => 6,
                'name' => 'Akumulasi Penyusutan - Mesin & Peralatan',
                'code' => '1-10754',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'company_id' => 1,
                'category_id' => 6,
                'name' => 'Akumulasi Penyusutan - Peralatan Kantor',
                'code' => '1-10755',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'company_id' => 1,
                'category_id' => 6,
                'name' => 'Akumulasi Penyusutan - Aset Sewa Guna Usaha',
                'code' => '1-10756',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'company_id' => 1,
                'category_id' => 6,
                'name' => 'Akumulasi Amortisasi',
                'code' => '1-10757',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'company_id' => 1,
                'category_id' => 7,
                'name' => 'Investasi',
                'code' => '1-10800',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'company_id' => 1,
                'category_id' => 8,
                'name' => 'Hutang Usaha',
                'code' => '2-20100',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'company_id' => 1,
                'category_id' => 8,
                'name' => 'Hutang Belum Ditagih',
                'code' => '2-20101',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang Lain Lain',
                'code' => '2-20200',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang Gaji',
                'code' => '2-20201',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang Deviden',
                'code' => '2-20202',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Pendapatan Diterima Di Muka',
                'code' => '2-20203',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang Konsinyasi',
                'code' => '2-20205',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Sarana Kantor Terhutang',
                'code' => '2-20301',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Bunga Terhutang',
                'code' => '2-20302',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Biaya Terhutang Lainnya',
                'code' => '2-20399',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang Bank',
                'code' => '2-20400',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'PPN Keluaran',
                'code' => '2-20500',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang Pajak - PPh 21',
                'code' => '2-20501',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang Pajak - PPh 22',
                'code' => '2-20502',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang Pajak - PPh 23',
                'code' => '2-20503',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang Pajak - PPh 29',
                'code' => '2-20504',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang Pajak Lainnya',
                'code' => '2-20599',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Hutang dari Pemegang Saham',
                'code' => '2-20600',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'company_id' => 1,
                'category_id' => 9,
                'name' => 'Kewajiban Lancar Lainnya',
                'code' => '2-20601',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'company_id' => 1,
                'category_id' => 10,
                'name' => 'Kewajiban Manfaat Karyawan',
                'code' => '2-20700',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'company_id' => 1,
                'category_id' => 11,
                'name' => 'Modal Saham',
                'code' => '3-30000',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'company_id' => 1,
                'category_id' => 11,
                'name' => 'Tambahan Modal Disetor',
                'code' => '3-30001',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'company_id' => 1,
                'category_id' => 11,
                'name' => 'Laba Ditahan',
                'code' => '3-30100',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'company_id' => 1,
                'category_id' => 11,
                'name' => 'Deviden',
                'code' => '3-30200',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'company_id' => 1,
                'category_id' => 11,
                'name' => 'Pendapatan Komprehensif Lainnya',
                'code' => '3-30300',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'company_id' => 1,
                'category_id' => 11,
                'name' => 'Ekuitas Saldo Awal',
                'code' => '3-30999',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'company_id' => 1,
                'category_id' => 12,
                'name' => 'Pendapatan',
                'code' => '4-40000',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'company_id' => 1,
                'category_id' => 12,
                'name' => 'Diskon Penjualan',
                'code' => '4-40100',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'company_id' => 1,
                'category_id' => 12,
                'name' => 'Retur Penjualan',
                'code' => '4-40200',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'company_id' => 1,
                'category_id' => 12,
                'name' => 'Pendapatan Belum Ditagih',
                'code' => '4-40201',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'company_id' => 1,
                'category_id' => 13,
                'name' => 'Beban Pokok Pendapatan',
                'code' => '5-50000',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'company_id' => 1,
                'category_id' => 13,
                'name' => 'Diskon Pembelian',
                'code' => '5-50100',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'company_id' => 1,
                'category_id' => 13,
                'name' => 'Retur Pembelian',
                'code' => '5-50200',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'company_id' => 1,
                'category_id' => 13,
                'name' => 'Pengiriman & Pengangkutan',
                'code' => '5-50300',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'company_id' => 1,
                'category_id' => 13,
                'name' => 'Biaya Impor',
                'code' => '5-50400',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'company_id' => 1,
                'category_id' => 13,
                'name' => 'Biaya Produksi',
                'code' => '5-50500',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Iklan & Promosi',
                'code' => '6-60001',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Komisi & Fee',
                'code' => '6-60002',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Bensin, Tol dan Parkir - Penjualan',
                'code' => '6-60003',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Perjalanan Dinas - Penjualan',
                'code' => '6-60004',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Komunikasi - Penjualan',
                'code' => '6-60005',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Marketing Lainnya',
                'code' => '6-60006',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Biaya MDR Penjualan',
                'code' => '6-60007',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Gaji',
                'code' => '6-60101',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Upah',
                'code' => '6-60102',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Makanan & Transportasi',
                'code' => '6-60103',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Lembur',
                'code' => '6-60104',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Pengobatan',
                'code' => '6-60105',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'THR & Bonus',
                'code' => '6-60106',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Jamsostek',
                'code' => '6-60107',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Insentif',
                'code' => '6-60108',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Pesangon',
                'code' => '6-60109',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Manfaat dan Tunjangan Lain',
                'code' => '6-60110',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Donasi',
                'code' => '6-60200',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Hiburan',
                'code' => '6-60201',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Bensin, Tol dan Parkir - Umum',
                'code' => '6-60202',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Perbaikan & Pemeliharaan',
                'code' => '6-60203',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Perjalanan Dinas - Umum',
                'code' => '6-60204',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Makanan',
                'code' => '6-60205',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Komunikasi - Umum',
                'code' => '6-60206',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Iuran & Langganan',
                'code' => '6-60207',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Asuransi',
                'code' => '6-60208',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Legal & Profesional',
                'code' => '6-60209',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Beban Manfaat Karyawan',
                'code' => '6-60210',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Sarana Kantor',
                'code' => '6-60211',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Pelatihan & Pengembangan',
                'code' => '6-60212',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Beban Piutang Tak Tertagih',
                'code' => '6-60213',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Pajak dan Perizinan',
                'code' => '6-60214',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Denda',
                'code' => '6-60215',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Pengeluaran Barang Rusak',
                'code' => '6-60216',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Listrik',
                'code' => '6-60217',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Air',
                'code' => '6-60218',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'IPL',
                'code' => '6-60219',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Langganan Software',
                'code' => '6-60220',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Beban Kantor',
                'code' => '6-60300',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Alat Tulis Kantor & Printing',
                'code' => '6-60301',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Bea Materai',
                'code' => '6-60302',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Keamanan dan Kebersihan',
                'code' => '6-60303',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 112,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Supplies dan Material',
                'code' => '6-60304',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 113,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Pemborong',
                'code' => '6-60305',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 114,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Biaya Sewa - Bangunan',
                'code' => '6-60400',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 115,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Biaya Sewa - Kendaraan',
                'code' => '6-60401',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 116,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Biaya Sewa - Operasional',
                'code' => '6-60402',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 117,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Biaya Sewa - Lain - lain',
                'code' => '6-60403',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 118,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Penyusutan - Bangunan',
                'code' => '6-60500',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 119,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Penyusutan - Perbaikan Bangunan',
                'code' => '6-60501',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 120,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Penyusutan - Kendaraan',
                'code' => '6-60502',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 121,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Penyusutan - Mesin & Peralatan',
                'code' => '6-60503',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 122,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Penyusutan - Peralatan Kantor',
                'code' => '6-60504',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 123,
                'company_id' => 1,
                'category_id' => 14,
                'name' => 'Penyusutan - Aset Sewa Guna Usaha',
                'code' => '6-60599',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 124,
                'company_id' => 1,
                'category_id' => 15,
                'name' => 'Pendapatan Bunga - Bank',
                'code' => '7-70000',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 125,
                'company_id' => 1,
                'category_id' => 15,
                'name' => 'Pendapatan Bunga - Deposito',
                'code' => '7-70001',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 126,
                'company_id' => 1,
                'category_id' => 15,
                'name' => 'Pendapatan Komisi - Barang Konsinyasi',
                'code' => '7-70002',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 127,
                'company_id' => 1,
                'category_id' => 15,
                'name' => 'Pembulatan',
                'code' => '7-70003',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 128,
                'company_id' => 1,
                'category_id' => 15,
                'name' => 'Pendapatan Lain - lain',
                'code' => '7-70099',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 129,
                'company_id' => 1,
                'category_id' => 15,
                'name' => 'Pendapatan lainnya (Service Charge)',
                'code' => '7-70100',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 130,
                'company_id' => 1,
                'category_id' => 15,
                'name' => 'Biaya Tambahan Pelanggan',
                'code' => '7-70101',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 131,
                'company_id' => 1,
                'category_id' => 16,
                'name' => 'Beban Bunga',
                'code' => '8-80000',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 132,
                'company_id' => 1,
                'category_id' => 16,
                'name' => 'Provisi',
                'code' => '8-80001',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 133,
                'company_id' => 1,
                'category_id' => 16,
                'name' => '(Laba)/Rugi Pelepasan Aset Tetap',
                'code' => '8-80002',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 134,
                'company_id' => 1,
                'category_id' => 16,
                'name' => 'Penyesuaian Persediaan',
                'code' => '8-80100',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 135,
                'company_id' => 1,
                'category_id' => 16,
                'name' => 'Beban Lain - lain',
                'code' => '8-80999',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 136,
                'company_id' => 1,
                'category_id' => 16,
                'name' => 'Revaluasi Bank',
                'code' => '8-81001',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 137,
                'company_id' => 1,
                'category_id' => 16,
                'name' => 'Laba/Rugi Selisih Kurs - Belum Direalisasikan',
                'code' => '8-81002',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 138,
                'company_id' => 1,
                'category_id' => 16,
                'name' => 'Laba/Rugi Selisih Kurs - Realisasikan',
                'code' => '8-81003',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 139,
                'company_id' => 1,
                'category_id' => 16,
                'name' => 'Beban Pajak - Kini',
                'code' => '9-90000',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => false,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 140,
                'company_id' => 1,
                'category_id' => 16,
                'name' => 'Beban Pajak - Tangguhan',
                'code' => '9-90001',
                'parent_id' => null,
                'is_parent' => false,
                'is_deletable' => true,
                'is_locked' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
